# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI/T0Statistics.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.return_2 = QtWidgets.QPushButton(self.centralwidget)
        self.return_2.setGeometry(QtCore.QRect(0, 190, 91, 51))
        self.return_2.setObjectName("return_2")
        self.save = QtWidgets.QPushButton(self.centralwidget)
        self.save.setGeometry(QtCore.QRect(0, 240, 91, 51))
        self.save.setObjectName("save")
        self.new_2 = QtWidgets.QPushButton(self.centralwidget)
        self.new_2.setGeometry(QtCore.QRect(0, 290, 91, 51))
        self.new_2.setObjectName("new_2")
        self.reselect = QtWidgets.QPushButton(self.centralwidget)
        self.reselect.setGeometry(QtCore.QRect(0, 340, 91, 51))
        self.reselect.setObjectName("reselect")
        self.N = QtWidgets.QPushButton(self.centralwidget)
        self.N.setGeometry(QtCore.QRect(0, 390, 91, 51))
        self.N.setObjectName("N")
        self.I = QtWidgets.QPushButton(self.centralwidget)
        self.I.setGeometry(QtCore.QRect(0, 440, 91, 51))
        self.I.setObjectName("I")
        self.K = QtWidgets.QPushButton(self.centralwidget)
        self.K.setGeometry(QtCore.QRect(0, 490, 91, 51))
        self.K.setObjectName("KDE")
        self.P = QtWidgets.QPushButton(self.centralwidget)
        self.P.setGeometry(QtCore.QRect(0, 540, 91, 51))
        self.P.setObjectName("Power")
        
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.Tsize =[580, 190, 220, 419]
        self.tableWidget.setGeometry(QtCore.QRect(self.Tsize[0], self.Tsize[1], self.Tsize[2], self.Tsize[3]))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(13)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.Isize =[91, 190, 490, 450]
        self.photo = QtWidgets.QLabel(self.centralwidget)
        self.photo.setGeometry(QtCore.QRect(self.Isize[0], self.Isize[1], self.Isize[2], self.Isize[3]))
        self.photo.setScaledContents(True)
        self.photo.setObjectName("photo")
        
        self.box = QtWidgets.QComboBox(self.centralwidget)
        self.box.addItems(['red','blue','green','yellow','cyan','magenta','gray','black','silver','maroon','olive','lime','purple','teal','navy'])
        self.box.setGeometry(0,130,91,30)
        
        self.box2 = QtWidgets.QComboBox(self.centralwidget)
        self.box2.addItems(['o','^','s','*','D','P','X'])
        self.box2.setGeometry(0,160,91,30)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.return_2.setText(_translate("MainWindow", "Return"))
        self.save.setText(_translate("MainWindow", "Save"))
        self.new_2.setText(_translate("MainWindow", "New"))
        self.reselect.setText(_translate("MainWindow", "Reselect"))
        self.N.setText(_translate("MainWindow", "Normal"))
        self.I.setText(_translate("MainWindow", "Inverse"))
        self.K.setText(_translate("MainWindow", "KDE"))
        self.P.setText(_translate("MainWindow", "Power"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Sample#"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Min"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "IRR"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "J"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "J Std"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "39/36 Int"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "39/36 Int std"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "36/40 Int"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "36/40 Int std"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "MSWD"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "WMA"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "Int age"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "Int age std"))
        

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

